name: Daily News Agent
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-news-agent:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd ..
          pip install -e .

      - name: Run
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_AUTH_CODE: ${{ secrets.EMAIL_AUTH_CODE }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          DASHSCOPE_API_KEY: ${{ secrets.DASHSCOPE_API_KEY }}
        run: python ../main/run_graph.py